name: flutter_aad_oauth
description: A Flutter OAuth package for performing user authentication against Azure Active Directory OAuth2 v2.0 endpoint.
version: 2.3.0
homepage: https://github.com/p-stannis/flutter_aad_oauth

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  webview_flutter: ^3.0.1
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  universal_html: ^2.0.8
  platform: ^3.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  # plugin:
  #   platforms:
  #     android:
  #       package: com.example.flutter_aad_oauth
  #       pluginClass: flutter_aad_oauth        
  #     ios:
  #       pluginClass: flutter_aad_oauth
  #     web:
  #       pluginClass: flutter_aad_oauth
  #       fileName: flutter_aad_oauth_web.dart